In [221]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.cross_validation import train_test_split
from sklearn import preprocessing
from sklearn.ensemble import RandomForestRegressor

# 1. load data

In [222]:
train_df = pd.read_csv("../input/train.csv")
print(train_df.describe())
print(train_df.head())
print(train_df.info())

                Id   MSSubClass  LotFrontage        LotArea  OverallQual  \
count  1460.000000  1460.000000  1201.000000    1460.000000  1460.000000
mean    730.500000    56.897260    70.049958   10516.828082     6.099315
std     421.610009    42.300571    24.284752    9981.264932     1.382997
min       1.000000    20.000000    21.000000    1300.000000     1.000000
25%     365.750000    20.000000    59.000000    7553.500000     5.000000
50%     730.500000    50.000000    69.000000    9478.500000     6.000000
75%    1095.250000    70.000000    80.000000   11601.500000     7.000000
max    1460.000000   190.000000   313.000000  215245.000000    10.000000

       OverallCond    YearBuilt  YearRemodAdd   MasVnrArea   BsmtFinSF1  \
count  1460.000000  1460.000000   1460.000000  1452.000000  1460.000000
mean      5.575342  1971.267808   1984.865753   103.685262   443.639726
std       1.112799    30.202904     20.645407   181.066207   456.098091
min       1.000000  1872.000000   1950.000000     0.000000     0.000000
25%       5.000000  1954.000000   1967.000000     0.000000     0.000000
50%       5.000000  1973.000000   1994.000000     0.000000   383.500000
75%       6.000000  2000.000000   2004.000000   166.000000   712.250000
max       9.000000  2010.000000   2010.000000  1600.000000  5644.000000

           ...         WoodDeckSF  OpenPorchSF  EnclosedPorch    3SsnPorch  \
count      ...        1460.000000  1460.000000    1460.000000  1460.000000
mean       ...          94.244521    46.660274      21.954110     3.409589
std        ...         125.338794    66.256028      61.119149    29.317331
min        ...           0.000000     0.000000       0.000000     0.000000
25%        ...           0.000000     0.000000       0.000000     0.000000
50%        ...           0.000000    25.000000       0.000000     0.000000
75%        ...         168.000000    68.000000       0.000000     0.000000
max        ...         857.000000   547.000000     552.000000   508.000000

       ScreenPorch     PoolArea       MiscVal       MoSold       YrSold  \
count  1460.000000  1460.000000   1460.000000  1460.000000  1460.000000
mean     15.060959     2.758904     43.489041     6.321918  2007.815753
std      55.757415    40.177307    496.123024     2.703626     1.328095
min       0.000000     0.000000      0.000000     1.000000  2006.000000
25%       0.000000     0.000000      0.000000     5.000000  2007.000000
50%       0.000000     0.000000      0.000000     6.000000  2008.000000
75%       0.000000     0.000000      0.000000     8.000000  2009.000000
max     480.000000   738.000000  15500.000000    12.000000  2010.000000

           SalePrice
count    1460.000000
mean   180921.195890
std     79442.502883
min     34900.000000
25%    129975.000000
50%    163000.000000
75%    214000.000000
max    755000.000000

[8 rows x 38 columns]
   Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg
1   2          20       RL         80.0     9600   Pave   NaN      Reg
2   3          60       RL         68.0    11250   Pave   NaN      IR1
3   4          70       RL         60.0     9550   Pave   NaN      IR1
4   5          60       RL         84.0    14260   Pave   NaN      IR1

  LandContour Utilities    ...     PoolArea PoolQC Fence MiscFeature MiscVal  \
0         Lvl    AllPub    ...            0    NaN   NaN         NaN       0
1         Lvl    AllPub    ...            0    NaN   NaN         NaN       0
2         Lvl    AllPub    ...            0    NaN   NaN         NaN       0
3         Lvl    AllPub    ...            0    NaN   NaN         NaN       0
4         Lvl    AllPub    ...            0    NaN   NaN         NaN       0

  MoSold YrSold  SaleType  SaleCondition  SalePrice
0      2   2008        WD         Normal     208500
1      5   2007        WD         Normal     181500
2      9   2008        WD         Normal     223500
3      2   2006        WD        Abnorml     140000
4     12   2008        WD         Normal     250000

[5 rows x 81 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
Id               1460 non-null int64
MSSubClass       1460 non-null int64
MSZoning         1460 non-null object
LotFrontage      1201 non-null float64
LotArea          1460 non-null int64
Street           1460 non-null object
Alley            91 non-null object
LotShape         1460 non-null object
LandContour      1460 non-null object
Utilities        1460 non-null object
LotConfig        1460 non-null object
LandSlope        1460 non-null object
Neighborhood     1460 non-null object
Condition1       1460 non-null object
Condition2       1460 non-null object
BldgType         1460 non-null object
HouseStyle       1460 non-null object
OverallQual      1460 non-null int64
OverallCond      1460 non-null int64
YearBuilt        1460 non-null int64
YearRemodAdd     1460 non-null int64
RoofStyle        1460 non-null object
RoofMatl         1460 non-null object
Exterior1st      1460 non-null object
Exterior2nd      1460 non-null object
MasVnrType       1452 non-null object
MasVnrArea       1452 non-null float64
ExterQual        1460 non-null object
ExterCond        1460 non-null object
Foundation       1460 non-null object
BsmtQual         1423 non-null object
BsmtCond         1423 non-null object
BsmtExposure     1422 non-null object
BsmtFinType1     1423 non-null object
BsmtFinSF1       1460 non-null int64
BsmtFinType2     1422 non-null object
BsmtFinSF2       1460 non-null int64
BsmtUnfSF        1460 non-null int64
TotalBsmtSF      1460 non-null int64
Heating          1460 non-null object
HeatingQC        1460 non-null object
CentralAir       1460 non-null object
Electrical       1459 non-null object
1stFlrSF         1460 non-null int64
2ndFlrSF         1460 non-null int64
LowQualFinSF     1460 non-null int64
GrLivArea        1460 non-null int64
BsmtFullBath     1460 non-null int64
BsmtHalfBath     1460 non-null int64
FullBath         1460 non-null int64
HalfBath         1460 non-null int64
BedroomAbvGr     1460 non-null int64
KitchenAbvGr     1460 non-null int64
KitchenQual      1460 non-null object
TotRmsAbvGrd     1460 non-null int64
Functional       1460 non-null object
Fireplaces       1460 non-null int64
FireplaceQu      770 non-null object
GarageType       1379 non-null object
GarageYrBlt      1379 non-null float64
GarageFinish     1379 non-null object
GarageCars       1460 non-null int64
GarageArea       1460 non-null int64
GarageQual       1379 non-null object
GarageCond       1379 non-null object
PavedDrive       1460 non-null object
WoodDeckSF       1460 non-null int64
OpenPorchSF      1460 non-null int64
EnclosedPorch    1460 non-null int64
3SsnPorch        1460 non-null int64
ScreenPorch      1460 non-null int64
PoolArea         1460 non-null int64
PoolQC           7 non-null object
Fence            281 non-null object
MiscFeature      54 non-null object
MiscVal          1460 non-null int64
MoSold           1460 non-null int64
YrSold           1460 non-null int64
SaleType         1460 non-null object
SaleCondition    1460 non-null object
SalePrice        1460 non-null int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB
None

# 2. preprocessing data

In [223]:
# train_df = train_df.drop(["Alley", "PoolQC", "Fence", "MiscFeature", "Utilities", "Street", "EnclosedPorch",
#                          "ScreenPorch", "3SsnPorch", "PoolArea", "MiscVal", "SaleType", "WoodDeckSF", "OpenPorchSF",
#                          "Neighborhood", "LandSlope", "BldgType", 'LowQualFinSF'], axis=1)

In [224]:
item_label = {}
for key in train_df.keys():
    if train_df[key].dtype == object:
        item_label[key] = preprocessing.LabelEncoder().fit(train_df[key])
        train_df[key] = item_label[key].transform(train_df[key])

In [225]:
## clean data
drop_list = []
drop_list.append('Id')
for key in train_df.keys():
    tmp = train_df.loc[train_df[key] > 0, key].count()
    if tmp <1000:
        #print key, tmp
        drop_list.append(key)
    #print key, tmp
train_df = train_df.drop(drop_list, axis=1)

In [226]:
def FillNan(df):
    item = []
    for key in df.keys():
        if df.loc[df[key].isnull(), key].shape[0] != 0:
            item.append(key)
    
    for key in item:
        df_tmp = df.reindex_axis([key] + list([a for a in df.columns if a not in item]), axis=1)
    
        unkown_data = df_tmp.loc[df_tmp[key].isnull()]
    
        known_data = df_tmp.loc[df_tmp[key].notnull()]
        
        rfr = RandomForestRegressor(n_estimators=400, n_jobs=-1)
        
        rfr.fit(known_data.values[:, 1::], known_data.values[:, 0])
        predicts = rfr.predict(unkown_data.values[:, 1::])
        
        df.loc[(df[key].isnull()), key] = predicts
        print ("key:%s, known_data:%s" % (key, predicts))
    return df
#print train_df.columns.get_loc("MSSubClass")
FillNan(train_df)

key:LotFrontage, known_data:[  90.4425   79.02     86.75     59.415    65.4025   71.91     68.97
   61.325    98.3025   75.1225   97.0625   69.455    67.935    79.1025
   77.4575   62.995    58.6925  149.7775   79.0725   76.9825   46.2025
   94.6025   60.125    85.4025   68.8375   52.345    59.67     99.215
   59.2325   76.24    120.7975   77.4725   84.4675   24.63     75.7325
   66.98     37.105    79.04     81.0425   70.055   103.0125   63.66
   64.8425   71.54     70.665    81.7025   72.24     65.1075   70.89
  121.3025   62.1175   73.0625   64.695    78.2275   77.4875   76.49
  126.6275   61.865    54.41     90.5425   44.31     74.44     62.93
   62.91     73.415    80.5125   78.3775   61.6275   71.6975  121.9325
   69.4475   59.85     72.24     84.4525   51.4      81.3325   81.0625
   92.65     78.5075   86.515    52.89     63.065    44.055    50.68
   67.4175   34.3675  100.6025   93.855    62.9575   93.8825   68.575
   79.54     78.8675   78.125   100.7575   44.8125   80.335    69.975
   62.2925   50.335    36.88     84.445    76.58     78.965    62.94
   24.495    77.7925   66.775    79.52     60.1575   96.1725   95.8925
   77.51     71.13     39.1025   41.9125   35.08     36.965    70.045
   67.695    64.8875   49.6675   37.1325  134.45     78.4675   75.5475
   68.0325   64.6725   63.9075   61.83     76.885    79.0575   75.73
   98.8475   89.38     36.8975   94.6275   62.16     96.485    91.405
   76.2275   57.7775   43.465    95.275    65.1375   72.72     95.2725
   70.315   107.405    62.7325   77.8425   79.4375   65.91     57.0225
   70.22     71.8825   83.985   142.4825   85.0775   82.83     95.625
   86.4025   71.125    52.3025   85.0925   95.7325   67.98     27.89
   99.185    95.8075   83.9825   74.6125   83.6925   91.71     82.5225
   48.1725   69.6175  139.95     61.11    138.1475   70.71     67.2125
   76.1525   73.63     65.4375   77.8475   83.6825   66.82    140.1725
   92.88     21.0075   44.865    63.1775   62.6275   60.755    75.405
   69.955    79.81     76.6625   72.3925   73.7775   53.33     51.715
   79.7525   65.175    70.74     51.1375   96.8875  100.1325   33.2925
   73.265    63.005    84.03     85.96     86.7575   88.5525   43.465
   80.6425   74.1475   75.2     112.7325   82.51     82.3625   52.9725
   61.11     61.02     79.55     85.2575  103.5125   71.6375   59.3775
   64.39     82.7525   61.095    59.2125   76.105    84.395    83.545
   76.4575   80.69     54.3025   24.66     72.95     66.455    36.8425
   99.255    93.8875   98.7825   90.8525   76.66     97.1725   93.385
   88.3275   75.0875   95.3225   45.6575   37.035    58.5775   63.8625]
key:GarageYrBlt, known_data:[ 1962.8425  1927.9275  1978.9175  1933.4475  1996.9475  1969.1925  1929.46
  1944.4675  1938.695   1969.6375  2004.045   1929.585   1961.315
  1942.2425  1927.4825  1930.5725  1946.81    1945.695   1969.065
  1928.1025  1931.1925  1931.8425  1929.9975  1943.785   1930.5275  1973.79
  1961.6     1973.16    1927.92    1931.085   1927.41    1951.4825  1931.85
  1943.17    1989.9325  2007.0025  1973.4525  1930.355   1928.51    1942.7925
  1925.6175  1973.8325  1944.9925  1942.4875  1986.9425  1928.8325
  1920.7375  1929.2825  1974.8825  1923.0425  1976.76    1977.01    1966.685
  1928.7175  1953.2075  1929.805   1933.7375  1976.6475  1921.7775
  1969.2375  1924.1875  1947.805   1991.0475  1928.4925  1969.99    1947.44
  1961.6475  1951.2175  1970.325   1924.9375  1931.24    1970.7825
  1942.7975  1929.3875  1940.6425  1945.03    1928.7375  1984.9575
  1973.795   1970.915   2006.4125]

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LandContour,LotConfig,Neighborhood,Condition1,Condition2,...,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,60,3,65.0000,8450,1,3,4,5,2,2,...,2,548,5,5,2,2,2008,8,4,208500
1,20,3,80.0000,9600,1,3,2,24,1,2,...,2,460,5,5,2,5,2007,8,4,181500
2,60,3,68.0000,11250,1,3,4,5,2,2,...,2,608,5,5,2,9,2008,8,4,223500
3,70,3,60.0000,9550,1,3,0,6,2,2,...,3,642,5,5,2,2,2006,8,0,140000
4,60,3,84.0000,14260,1,3,2,15,2,2,...,3,836,5,5,2,12,2008,8,4,250000
5,50,3,85.0000,14115,1,3,4,11,2,2,...,2,480,5,5,2,10,2009,8,4,143000
6,20,3,75.0000,10084,1,3,4,21,2,2,...,2,636,5,5,2,8,2007,8,4,307000
7,60,3,90.4425,10382,1,3,0,14,4,2,...,2,484,5,5,2,11,2009,8,4,200000
8,50,4,51.0000,6120,1,3,4,17,0,2,...,2,468,2,5,2,4,2008,8,0,129900
9,190,3,50.0000,7420,1,3,0,3,0,0,...,1,205,3,5,2,1,2008,8,4,118000
10,20,3,70.0000,11200,1,3,4,19,2,2,...,1,384,5,5,2,2,2008,8,4,129500
11,60,3,85.0000,11924,1,3,4,16,2,2,...,3,736,5,5,2,7,2006,6,5,345000
12,20,3,79.0200,12968,1,3,4,19,2,2,...,1,352,5,5,2,9,2008,8,4,144000
13,20,3,91.0000,10652,1,3,4,5,2,2,...,3,840,5,5,2,8,2007,6,5,279500
14,20,3,86.7500,10920,1,3,0,12,2,2,...,1,352,5,5,2,5,2008,8,4,157000
15,45,4,51.0000,6120,1,3,0,3,2,2,...,2,576,5,5,2,7,2007,8,4,132000
16,20,3,59.4150,11241,1,3,1,12,2,2,...,2,480,5,5,2,3,2010,8,4,149000
17,90,3,72.0000,10791,1,3,4,19,2,2,...,2,516,5,5,2,10,2006,8,4,90000
18,20,3,66.0000,13695,1,3,4,20,5,2,...,2,576,5,5,2,6,2008,8,4,159000
19,20,3,70.0000,7560,1,3,4,12,2,2,...,1,294,5,5,2,5,2009,0,0,139000
20,60,3,101.0000,14215,1,3,0,16,2,2,...,3,853,5,5,2,11,2006,6,5,325300
21,45,4,57.0000,7449,1,0,4,9,2,2,...,1,280,5,5,0,6,2007,8,4,139400
22,20,3,75.0000,9742,1,3,4,5,2,2,...,2,534,5,5,2,9,2008,8,4,230000
23,120,4,44.0000,4224,1,3,4,10,2,2,...,2,572,5,5,2,6,2007,8,4,129900
24,20,3,65.4025,8246,1,3,4,19,2,2,...,1,270,5,5,2,5,2010,8,4,154000
25,20,3,110.0000,14230,1,3,0,16,2,2,...,3,890,5,5,2,7,2009,8,4,256300
26,20,3,60.0000,7200,1,3,0,12,2,2,...,2,576,5,5,2,5,2010,8,4,134800
27,20,3,98.0000,11478,1,3,4,16,2,2,...,3,772,5,5,2,5,2010,8,4,306000
28,20,3,47.0000,16321,1,3,1,12,2,2,...,1,319,5,5,2,12,2006,8,4,207500
29,30,4,60.0000,6324,1,3,4,3,1,7,...,1,240,2,5,2,5,2008,8,4,68500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1430,60,3,60.0000,21930,1,3,4,8,6,2,...,2,372,5,5,2,7,2006,8,4,192140
1431,120,3,45.6575,4928,1,3,4,13,2,2,...,2,440,5,5,2,10,2009,8,4,143750
1432,30,3,60.0000,10800,1,3,4,17,2,2,...,1,216,2,2,2,8,2007,8,4,64500
1433,60,3,93.0000,10261,1,3,4,8,2,2,...,2,451,5,5,2,5,2008,8,4,186500
1434,20,3,80.0000,17400,1,2,4,11,2,2,...,2,484,5,5,1,5,2006,8,4,160000
1435,20,3,80.0000,8400,1,3,4,12,2,2,...,2,462,5,5,2,7,2008,0,0,174000
1436,20,3,60.0000,9000,1,3,2,12,2,2,...,2,528,5,5,2,5,2007,8,4,120500
1437,20,3,96.0000,12444,1,3,2,16,2,2,...,3,774,5,5,2,11,2008,6,5,394617
1438,20,4,90.0000,7407,1,3,4,17,0,2,...,2,923,5,5,2,4,2010,8,4,149700
1439,60,3,80.0000,11584,1,3,4,14,2,2,...,2,550,5,5,2,11,2007,8,4,197000
1440,70,3,79.0000,11526,1,0,4,6,2,2,...,2,672,5,5,2,9,2008,8,4,191000
1441,120,4,37.0350,4426,1,3,4,5,2,2,...,2,420,5,5,2,5,2008,8,4,149300
1442,60,1,85.0000,11003,1,3,4,21,2,2,...,3,812,5,5,2,4,2009,8,4,310000
1443,30,3,58.5775,8854,1,3,4,3,2,2,...,1,192,2,4,1,5,2009,8,4,121000
1444,20,3,63.0000,8500,1,3,2,5,2,2,...,2,626,5,5,2,11,2007,8,4,179600
1445,85,3,70.0000,8400,1,3,4,19,2,2,...,1,240,5,5,2,5,2007,8,4,129000
1446,20,3,63.8625,26142,1,3,1,11,2,2,...,1,312,5,5,1,4,2010,8,4,157900
1447,60,3,80.0000,10000,1,3,4,5,2,2,...,2,556,5,5,2,12,2007,8,4,240000
1448,50,3,70.0000,11767,1,3,4,7,2,2,...,1,384,2,5,2,5,2007,8,4,112000
1449,180,4,21.0000,1533,1,3,4,10,2,2,...,0,0,0,0,2,8,2006,8,0,92000
1450,90,3,60.0000,9000,1,3,2,12,2,2,...,0,0,0,0,2,9,2009,8,4,136000
1451,20,3,78.0000,9262,1,3,4,21,2,2,...,3,840,5,5,2,5,2009,6,5,287090
1452,180,4,35.0000,3675,1,3,4,7,2,2,...,2,525,5,5,2,5,2006,8,4,145000
1453,20,3,90.0000,17217,1,3,4,11,2,2,...,0,0,0,0,2,7,2006,8,0,84500
1454,20,1,62.0000,7500,1,3,4,21,2,2,...,2,400,5,5,2,10,2009,8,4,185000
1455,60,3,62.0000,7917,1,3,4,8,2,2,...,2,460,5,5,2,8,2007,8,4,175000
1456,20,3,85.0000,13175,1,3,4,14,2,2,...,2,500,5,5,2,2,2010,8,4,210000
1457,70,3,66.0000,9042,1,3,4,6,2,2,...,1,252,5,5,2,5,2010,8,4,266500
1458,20,3,68.0000,9717,1,3,4,12,2,2,...,1,240,5,5,2,4,2010,8,4,142125
1459,20,3,75.0000,9937,1,3,4,7,2,2,...,1,276,5,5,2,6,2008,8,4,147500

### standrd scaler

In [227]:
train_X, test_X, train_y, test_y = train_test_split(train_df.values[:, :-1], train_df.values[:, -1], random_state=2016, test_size=.3)

In [228]:
lr = LinearRegression()
lr.fit(train_X, train_y)
lr.score(test_X, test_y)

0.81748012736039377

# Predict test

In [239]:
def predict_test(model):
    test_df = pd.read_csv("../input/test.csv")
    from sklearn.preprocessing import Imputer
    
    test_df = test_df.drop(drop_list, axis=1)
    
    print test_df.MSZoning
    
    # fill nan 
    # test_df = test_df.fillna(-1)

    for key in test_df.keys():
        #print key
        if test_df.loc[(test_df[key] == -1), key].count() != 0:
            tmp_mean = test_df[key].mean()
            test_df[key] = test_df[key].map(lambda x : tmp_mean if x == -1 else x)
            #print test_df[key].isnull()
    print test_df.info(), test_df['LotFrontage']
    for key in test_df.keys():
        if test_df[key].dtype == object:
            #print key, item_label.keys()
            if key in item_label:
                test_df[key] = item_label[key].transform(test_df[key])
                
    
    
predict_test(lr)

0            RH
1            RL
2            RL
3            RL
4            RL
5            RL
6            RL
7            RL
8            RL
9            RL
10           RH
11           RM
12           RM
13           RL
14           RL
15           RL
16           RL
17           RL
18           RL
19           RL
20           RL
21           RL
22           RL
23           RL
24           RL
25           RL
26           RL
27           RL
28           FV
29           FV
         ...
1429         RM
1430         RM
1431    C (all)
1432    C (all)
1433    C (all)
1434         RM
1435         RM
1436         RL
1437         RL
1438         RL
1439         RL
1440         RL
1441         RL
1442         RL
1443         RL
1444        NaN
1445         RM
1446         RM
1447         RL
1448         RL
1449         RM
1450         RM
1451         RL
1452         RM
1453         RM
1454         RM
1455         RM
1456         RL
1457         RL
1458         RL
Name: MSZoning, dtype: object

TypeError: cannot concatenate 'str' and 'int' objects

In [ ]:
a ={'a':1, 'b':2}
for i in a:
    print i